---
title: "Stats Computing Project 1"
author: "Collin McGuire"
date: "9/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Statistical Computing Project 1
###Collin McGuire

#####Initial Setup

First, we load the tidyverse package. Then we load in the Tidy Tuesday date from January 21, 2020, which we then save 

```{r Load Data}
library(tidyverse)
tuesdaydata <- tidytuesdayR::tt_load('2020-01-21') ## Load the Tidy Tuesday data from 2020-01-21 and save as tuesdaydata
spotify_songs <- tuesdaydata$spotify_songs
glimpse(spotify_songs)
```

#####Part 1

For this section, we will make use of the dplyr function to answer some exploratory data analysis questions about the Spotify song data


######1.

```{r Count}
library(dplyr)
songs <- as_tibble(spotify_songs)
songs <- arrange(songs, track_album_release_date) ## Arrange by date
songs %>%
  count(playlist_genre, sort = TRUE)
```

######2.

```{r Average Value}
songs %>%
  filter(playlist_genre == "latin") %>%
  summarize(energy = mean(energy, na.rm = TRUE), acousticness = mean(acousticness, na.rm = TRUE))
```

######3.

```{r Duration}
songs %>%
  group_by(playlist_genre) %>%
  summarize(duration_ms = mean(duration_ms, na.rm = TRUE))
```

######4. 

```{r Boxplots}
med <- summarize(songs, tempo = median(tempo, na.rm = TRUE))
tempo_set <- songs %>%
  mutate(tempo_cat = case_when(
    tempo >= med$tempo ~ "Fast",
    tempo < med$tempo ~ "Slow"
  ))

base <- tempo_set %>%
          ggplot(aes(tempo_cat, danceability))
base + geom_boxplot()
```

#####Part 2

```{r Part 2}
library(lubridate)
part2 <- distinct(spotify_songs,
                  track_name, track_artist,
                  .keep_all = TRUE)
year_data <- ymd(part2$track_album_release_date, quiet = FALSE, tz = NULL, truncated = 2)
only_year <- year(year_data)
post_1980 <- part2 %>%
  mutate(year_released = only_year) %>%
  filter(year_released >= 1980)
post_1980 <- post_1980 %>%
  mutate(duration_in_minutes = duration_ms / 60000)
average_by_year <- post_1980 %>%
  group_by(year_released) %>%
  summarize(loudness = mean(loudness, na.rm = TRUE),
            instrumentalness = mean(instrumentalness, na.rm = TRUE),
            danceability = mean(danceability, na.rm = TRUE),
            energy = mean(energy, na.rm = TRUE),
            speechiness = mean(speechiness, na.rm = TRUE),
            tempo = mean(tempo, na.rm = TRUE),)
average_by_year %>%
  pivot_longer(-year_released, names_to = "feature", values_to = "mean_score")
```

#####Part 3.
